apiVersion: v1
kind: Service
metadata:
  namespace: %VAR-NAMESPACE%
  labels:
    app: %VAR-APP%
  name: %VAR-NAME%
spec:
  ports:
  - name: "%VAR-PORT-NAME%"
    port: %VAR-PORT%
    targetPort: %VAR-TARGET-PORT%
  selector:
    app: %VAR-APP-SELECTOR%